version: 2.1

orbs:
  node: circleci/node@2.0.3

defaults: &default
  executor: 
    name: node/default

step_restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: npm install

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: npm run ls-lint
      - run: npm test --ci --runInBand
      - run: npm run test:report
  
  build: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: npm run build

workflows:
  version: 2
  ci:
    jobs:
      - test
