version: 2.1

orbs:
  node: circleci/node@1.1.6

step_restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package-lock.json" }}-1
      - v1-dependencies-

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: npm install

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
      - packages/compiler-core/node_modules
      - packages/compiler-sfc/node_modules
      - packages/vue/node_modules
    key: v1-dependencies-{{ checksum "package-lock.json" }}-1

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - *restore_cache
      - *install_deps
      - *save_cache
      - run: npm run ls-lint
      - run: npm test --ci --runInBand

workflows:
  version: 2
  ci:
    jobs:
      - test
